/// Flutter icons MetroAppFont
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MetroAppFont
///      fonts:
///       - asset: fonts/MetroAppFont.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MetroAppFont {
  MetroAppFont._();

  static const _kFontFam = 'MetroAppFont';

  static const IconData icon_actionbar_ruta = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData icon_chip_lineas_metro_1 = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData icon_chip_lineas_metro_2 = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData icon_chip_lineas_metro_3 = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData icon_chip_lineas_metro_4 = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData icon_chip_lineas_metro_5 = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData icon_chip_lineas_metro_6 = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData icon_chip_lineas_metro_7 = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData icon_chip_lineas_metro_8 = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData icon_chip_lineas_metro_9 = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData icon_chip_lineas_metro_12 = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData icon_chip_lineas_metro_a = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData icon_chip_lineas_metro_b = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData icon_drawer_metrobus = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData icon_drawer_trensuburbano = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData icon_drawer_pumabus = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData icon_drawer_trenligero = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData icon_drawer_metro = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData icon_bottombar_mapalineas = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData icon_bottombar_estaciones = const IconData(0xe814, fontFamily: _kFontFam);
}
